import type { BibleBookMeta } from "@/types/bible";

export const BIBLE_BOOKS_META: BibleBookMeta[] = [
  { id: "genesis", name: "Gênesis", abbrev: "Gn", order: 1 },
  { id: "exodo", name: "Êxodo", abbrev: "Ex", order: 2 },
  { id: "levitico", name: "Levítico", abbrev: "Lv", order: 3 },
  { id: "numeros", name: "Números", abbrev: "Nm", order: 4 },
  { id: "deuteronomio", name: "Deuteronômio", abbrev: "Dt", order: 5 },
  { id: "josue", name: "Josué", abbrev: "Js", order: 6 },
  { id: "juizes", name: "Juízes", abbrev: "Jz", order: 7 },
  { id: "rute", name: "Rute", abbrev: "Rt", order: 8 },
  { id: "1samuel", name: "1 Samuel", abbrev: "1Sm", order: 9 },
  { id: "2samuel", name: "2 Samuel", abbrev: "2Sm", order: 10 },
  { id: "1reis", name: "1 Reis", abbrev: "1Rs", order: 11 },
  { id: "2reis", name: "2 Reis", abbrev: "2Rs", order: 12 },
  { id: "1cronicas", name: "1 Crônicas", abbrev: "1Cr", order: 13 },
  { id: "2cronicas", name: "2 Crônicas", abbrev: "2Cr", order: 14 },
  { id: "esdras", name: "Esdras", abbrev: "Ed", order: 15 },
  { id: "neemias", name: "Neemias", abbrev: "Ne", order: 16 },
  { id: "ester", name: "Ester", abbrev: "Et", order: 17 },
  { id: "jo", name: "Jó", abbrev: "Jó", order: 18 },
  { id: "salmos", name: "Salmos", abbrev: "Sl", order: 19 },
  { id: "proverbios", name: "Provérbios", abbrev: "Pv", order: 20 },
  { id: "eclesiastes", name: "Eclesiastes", abbrev: "Ec", order: 21 },
  { id: "cantares", name: "Cânticos", abbrev: "Ct", order: 22 },
  { id: "isaias", name: "Isaías", abbrev: "Is", order: 23 },
  { id: "jeremias", name: "Jeremias", abbrev: "Jr", order: 24 },
  { id: "lamentacoes", name: "Lamentações", abbrev: "Lm", order: 25 },
  { id: "ezequiel", name: "Ezequiel", abbrev: "Ez", order: 26 },
  { id: "daniel", name: "Daniel", abbrev: "Dn", order: 27 },
  { id: "oseias", name: "Oséias", abbrev: "Os", order: 28 },
  { id: "joel", name: "Joel", abbrev: "Jl", order: 29 },
  { id: "amos", name: "Amós", abbrev: "Am", order: 30 },
  { id: "obadias", name: "Obadias", abbrev: "Ob", order: 31 },
  { id: "jonas", name: "Jonas", abbrev: "Jn", order: 32 },
  { id: "miqueias", name: "Miquéias", abbrev: "Mq", order: 33 },
  { id: "naum", name: "Naum", abbrev: "Na", order: 34 },
  { id: "habacuque", name: "Habacuque", abbrev: "Hc", order: 35 },
  { id: "sofonias", name: "Sofonias", abbrev: "Sf", order: 36 },
  { id: "ageu", name: "Ageu", abbrev: "Ag", order: 37 },
  { id: "zacarias", name: "Zacarias", abbrev: "Zc", order: 38 },
  { id: "malaquias", name: "Malaquias", abbrev: "Ml", order: 39 },
  { id: "mateus", name: "Mateus", abbrev: "Mt", order: 40 },
  { id: "marcos", name: "Marcos", abbrev: "Mc", order: 41 },
  { id: "lucas", name: "Lucas", abbrev: "Lc", order: 42 },
  { id: "joao", name: "João", abbrev: "Jo", order: 43 },
  { id: "atos", name: "Atos", abbrev: "At", order: 44 },
  { id: "romanos", name: "Romanos", abbrev: "Rm", order: 45 },
  { id: "1corintios", name: "1 Coríntios", abbrev: "1Co", order: 46 },
  { id: "2corintios", name: "2 Coríntios", abbrev: "2Co", order: 47 },
  { id: "galatas", name: "Gálatas", abbrev: "Gl", order: 48 },
  { id: "efesios", name: "Efésios", abbrev: "Ef", order: 49 },
  { id: "filipenses", name: "Filipenses", abbrev: "Fp", order: 50 },
  { id: "colossenses", name: "Colossenses", abbrev: "Cl", order: 51 },
  {
    id: "1tessalonicenses",
    name: "1 Tessalonicenses",
    abbrev: "1Ts",
    order: 52,
  },
  {
    id: "2tessalonicenses",
    name: "2 Tessalonicenses",
    abbrev: "2Ts",
    order: 53,
  },
  { id: "1timoteo", name: "1 Timóteo", abbrev: "1Tm", order: 54 },
  { id: "2timoteo", name: "2 Timóteo", abbrev: "2Tm", order: 55 },
  { id: "tito", name: "Tito", abbrev: "Tt", order: 56 },
  { id: "filemom", name: "Filemom", abbrev: "Fm", order: 57 },
  { id: "hebreus", name: "Hebreus", abbrev: "Hb", order: 58 },
  { id: "tiago", name: "Tiago", abbrev: "Tg", order: 59 },
  { id: "1pedro", name: "1 Pedro", abbrev: "1Pe", order: 60 },
  { id: "2pedro", name: "2 Pedro", abbrev: "2Pe", order: 61 },
  { id: "1joao", name: "1 João", abbrev: "1Jo", order: 62 },
  { id: "2joao", name: "2 João", abbrev: "2Jo", order: 63 },
  { id: "3joao", name: "3 João", abbrev: "3Jo", order: 64 },
  { id: "judas", name: "Judas", abbrev: "Jd", order: 65 },
  { id: "apocalipse", name: "Apocalipse", abbrev: "Ap", order: 66 },
];

export const BIBLE_BOOKS_META_BY_ID = Object.fromEntries(
  BIBLE_BOOKS_META.map((book) => [book.id, book]),
);
